### PR TITLE
Fix coverage reporting

### PR DESCRIPTION
**Pull request by MichaelClerx**
See #25

### CODE REVIEW

**Comment by MichaelClerx** [comment]
Uhm... Why is the coverage config file stored inside the python module there??

**Comment by jonc125** [comment]
Ah, though having approved, I've just realised that the coverage is reported at 0% again...

**Comment by MichaelClerx** [comment]
OK. It worked locally because I was still using the old -e install. Now copying the cellmlmanip configuration but to no avail

**Comment by MichaelClerx** [comment]
I'm happy for `tests` to be a module anyway, so that the tests can e.g. share code

**Comment by MichaelClerx** [comment]
OK. Now for some reason the Cython classes weren't found. Re-running and hoping it works this time round :-/

**Comment by MichaelClerx** [comment]
This makes me want to just install with `-e` again @jonc125 ! Our users can't pip install anyway, because they need numpy and cython pre-installed

**Comment by MichaelClerx** [comment]
Weird error this! Can't recreate it locally, following the same steps as travis

**Comment by MichaelClerx** [comment]
Any ideas @jonc125 ? I don't have much experience with Cython

**Pull request closed without merging**
