### PR TITLE
Parse more parts of the model interface

### PR DESCRIPTION
**Pull request by MichaelClerx**
For
- Running `graphstate` on models requiring unit conversion #22 
- Running `test_while_loop` on a generated model #30

### CODE REVIEW

**Comment by MichaelClerx** [comment]
https://github.com/ModellingWebLab/weblab-fc/blob/30-test-while-loop/fc/protocol.py#L624-L666

@jonc125 do the comments I put in here make sense?

@skeating this is where we do the model manipulation - and I think input/output unit conversion - in `fc`. One difficulty is that the information to do this (the ModelInterface class) didn't exist before (pycml read the protocol too) so I'm extracting required info from the parser and sticking it in the ModelInterface as I go along

**Comment by jonc125** [comment]
> do the comments I put in here make sense?

They're along the right lines. Some thoughts quickly:

* "Create protocol unit store" is probably best done when the protocol is parsed/created - it's not model-specific, and indeed should be independent of the model
* Outputs can be of any type. And handling their units will be done by cellmlmanip's `add_output` method.
* I don't think the state_variable output should be handled specially here; just treat it as a standard ontology term (but like concentration, it can annotate multiple variables: vector outputs in pycml terms).
* The `define` statement handling should also modify the model, but I guess that's implicit?
* And of course there are some steps missing, but we're not worrying about those yet.

**Comment by MichaelClerx** [comment]
Some notes after a chat with @skeating :

- This branch/PR can be repurposed as the unit-conversion branch, as it contains some work on extracting the required info from the model interface and getting it to the cellmlmanip model
- There's a test in the branch called [test_generated_model_while_loop](https://github.com/ModellingWebLab/weblab-fc/blob/30-test-while-loop/test/test_generated_model_while_loop.py) that doesn't terminate, so will have to be disabled/removed for unit conversion work

- Information from the FC protocol is parsed in the [CompactSyntaxParser](https://github.com/ModellingWebLab/weblab-fc/blob/30-test-while-loop/fc/parsing/CompactSyntaxParser.py), but not all required info is currently read in (because pycml used to do this).
- Instead, the required info can be seen in the commented out `_xml` methods in the CompactSyntaxParser, and transferred to the `_expr` methods
- The _expr method returns unstructured dicts, see e.g. https://github.com/ModellingWebLab/weblab-fc/blob/30-test-while-loop/fc/parsing/CompactSyntaxParser.py#L482-L509

- In `protocol.py`, the info from the parser is combined (because protocols can import other protocols, so there's several parsing trees potentially), and then stored in the protocol
- I've started making a more structured class for the [ModelInterface data](https://github.com/ModellingWebLab/weblab-fc/blob/30-test-while-loop/fc/protocol.py#L750). 
  - This may or may not be a good idea, maybe a style thing? Up to you to expand, continue, or ditch this approach!

- The cellmlmanipmodel is created in [protocol.set_model](https://github.com/ModellingWebLab/weblab-fc/blob/30-test-while-loop/fc/protocol.py#L592)
- I've outlined a basic scheme of how to read inputs and where to do unit conversion here (see also discussion above)

Hope that's useful! @jonc125 feel free to directly modify this message if there's any major mistakes :-)

**Comment by jonc125** [comment]
I'm not going to push any changes to this branch as I'm not sure whether @skeating has any uncommitted code. But some thoughts:
* The `ModelInterface` class etc. should probably move to a new file in the `parsing` subfolder? And then the parser _expr methods can return instances of these directly?
* Seems like `exposeNamedParameters` is no longer used so we can get rid of that!

I could work on these, along with starting to parse the `define` stuff, in a separate branch building off this?

**Comment by MichaelClerx** [comment]
Sounds great! Or you could continue in this branch I guess (Sarah mentioned she didn't get very far)

**Comment by jonc125** [comment]
@MichaelClerx I forgot to create a separate branch before pushing https://github.com/ModellingWebLab/weblab-fc/pull/73/files/bc4cf9af6050a66bd25f676d010303253b3446a9..716bdaa4842a25150c39dc1ef2e38aa6edc9e535, but they're actually working on the topic of this PR, so ... :)

Does this look like a reasonable approach to be taking?

**Comment by MichaelClerx** [comment]
Yup, that looks sensible to me!

**Comment by jonc125** [comment]
@MichaelClerx I think we could merge this, except some units stuff [is failing](https://travis-ci.com/ModellingWebLab/weblab-fc/builds/147761160) :( Looks like I'm not allowed to pass e.g. 'millivolt' as a unit definition string, which is surprising me. Any suggestions?

**Comment by jonc125** [comment]
Hooray! Graph state and while loop protocols pass (albeit without unit conversions)!

**Pull request merged**
